<h1>AUTHOR - NILUTPOL KASHYAP </H1>

In [3]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

print("Done Importing Libraries!!!!")

Done Importing Libraries!!!!


In [54]:
lena_img = cv2.imread("lena.jpg", 1 )
print(lena_img)

#COLOR FORMAT
# 0 - cv2.IMREAD_GRAYSCALE
# 1 - cv2.IMREAD_COLOR - DEFAULT
# -1 - cv2.IMREAD_UNCHANGED - Alpha Channel

[[[128 138 225]
  [127 137 224]
  [126 136 223]
  ...
  [126 146 234]
  [110 129 220]
  [ 86 104 197]]

 [[127 138 222]
  [127 137 224]
  [127 137 224]
  ...
  [130 150 235]
  [112 131 218]
  [ 83 102 189]]

 [[127 138 222]
  [127 137 224]
  [128 138 225]
  ...
  [127 148 230]
  [112 133 215]
  [ 85 105 190]]

 ...

 [[ 55  21  82]
  [ 54  20  81]
  [ 62  28  92]
  ...
  [ 82  71 175]
  [ 78  68 175]
  [ 74  65 175]]

 [[ 55  18  80]
  [ 54  20  81]
  [ 67  33  94]
  ...
  [ 82  69 177]
  [ 82  70 182]
  [ 81  72 183]]

 [[ 56  19  81]
  [ 58  21  83]
  [ 69  35  96]
  ...
  [ 81  68 178]
  [ 83  71 183]
  [ 84  74 188]]]


In [13]:
print(lena_img.shape)

(512, 512)


In [ ]:
gray_img = cv2.cvtColor(lena_img, cv2.COLOR_BGR2GRAY)
print(lena)

In [33]:
cv2.imshow("lena", lena_img)
cv2.waitKey(1000)
#cv2.destroyAllWindows()
cv2.destroyWindow("lena")

In [18]:
cv2.imwrite("lena_new.jpg", lena_img)

True

In [32]:
lena_new = cv2.imread("lena_new.jpg", -1)

cv2.imshow("lena_new", lena_new)
cv2.waitKey(1000)
cv2.destroyWindow("lena_new")

In [34]:
lena_img2 = cv2.imread("lena.jpg", 0)
cv2.imshow("lena_image", lena_img2)

k = cv2.waitKey(0) & 0xFF         #0xFF is mask for 64-bit machines
if k == 27:      # Esc key
    cv2.destroyWindow("lena_image")

In [40]:
lena_invert  = cv2.flip(lena_img, flipCode = -1)
cv2.imshow("lena_inverted", lena_invert)

k = cv2.waitKey(0) & 0xFF
if k == 27:
    cv2.destroyWindow("lena_inverted")

In [51]:
lena_img = cv2.imread("lena.jpg", cv2.IMREAD_COLOR)
cv2.imshow("lena_img", lena_img)

k = cv2.waitKey(0) & 0xFF

if k == 27:
    cv2.destroyWindow("lena_img")
    print("Image Frame closed!!")
elif k == ord('s'):
    cv2.imwrite("lena2.jpg", lena_img)
    cv2.destroyWindow("lena_img")
    print("Image saved!!")
elif k == ord('i'):
    lena_invert = cv2.flip(lena_img, flipCode = -1)
    cv2.imwrite("lena_invert2.jpg", lena_invert)
    cv2.destroyWindow("lena_img")
    print("Inverted image saved!!")

Inverted image saved!!


In [52]:
cv2.imshow("lena", lena_img)
cv2.waitKey(2000)
cv2.destroyWindow("lena")

lena_gray = cv2.cvtColor(lena_img, cv2.COLOR_BGR2GRAY)cv2.imshow