In [2]:
import numpy as np
import cv2

In [4]:
def display(window_name, canvas):
    cv2.imshow(window_name, canvas)
    cv2.waitKey(0)
    cv2.destroyWindow(window_name)

In [20]:
image = cv2.imread("chilli.jpg", 0)
display("image", image)

In [21]:
image.shape

(512, 512)

In [9]:
edge = np.zeros((image.shape[:2]))
display("edge", edge)

In [10]:
edge.shape

(512, 512)

In [11]:
h, w = image.shape[:2]
print("Height : {}, width : {}".format(h,w))

Height : 512, width : 512


In [13]:
sobelx = [[1,0,-1],[2,0,-2],[1,0,-1],]
print(sobelx)

[[1, 0, -1], [2, 0, -2], [1, 0, -1]]


In [14]:
sobelx = np.asarray(sobelx)
print(sobelx)

[[ 1  0 -1]
 [ 2  0 -2]
 [ 1  0 -1]]


In [15]:
sobelx.shape

(3, 3)

In [36]:
for i in range(1,w-1):
    for j in range(1, h-1):
        
        a0 = image[i-1,j-1] * sobelx[0,0]
        a1 = image[i-1,j] * sobelx[0,1]
        a2 = image[i-1, j+1] * sobelx[0,2]
        a3 = image[i, j-1] * sobelx[1,0]
        a4 = image[i, j] * sobelx[1,1]
        a5 = image[i, j+1] * sobelx[1,2]
        a6 = image[i+1, j-1] * sobelx[2,0]
        a7 = image[i+1, j] * sobelx[2,1]
        a8 = image[i+1, j+1] * sobelx[2,2]
        alist = [a0,a1,a2,a3,a4,a5,a6,a7,a8]
        asum = sum(alist)
        
        edge[i,j] = asum

In [33]:
b1 = 43
b2 = 5
b3 = 10
l = [b1,b2,b3]
print(l)
print(sum(l))

[43, 5, 10]
58


In [50]:
display("edge", edge)

In [43]:
sobely = [[1,2,1],[0,0,0],[-1,-2,-1]]
print(sobely)

[[1, 2, 1], [0, 0, 0], [-1, -2, -1]]


In [44]:
sobely = np.asarray(sobely)
print(sobely)

[[ 1  2  1]
 [ 0  0  0]
 [-1 -2 -1]]


In [45]:
sobely.shape

(3, 3)

In [46]:
edge2 = np.zeros((image.shape[:2]))
print(edge2.shape)

(512, 512)


In [47]:
display("edge2", edge2)

In [48]:
for i in range(1,w-1):
    for j in range(1, h-1):
        
        a0 = image[i-1,j-1] * sobely[0,0]
        a1 = image[i-1,j] * sobely[0,1]
        a2 = image[i-1, j+1] * sobely[0,2]
        a3 = image[i, j-1] * sobely[1,0]
        a4 = image[i, j] * sobely[1,1]
        a5 = image[i, j+1] * sobely[1,2]
        a6 = image[i+1, j-1] * sobely[2,0]
        a7 = image[i+1, j] * sobely[2,1]
        a8 = image[i+1, j+1] * sobely[2,2]
        alist2 = [a0,a1,a2,a3,a4,a5,a6,a7,a8]
        asum2 = sum(alist2)
        
        edge2[i,j] = asum2

In [51]:
display("edge2", edge2)

In [52]:
final = cv2.add(edge, edge2)
display("final", final)